import { useEffect, useState } from 'react'
import { api, euro } from '../api.js'

const HOURS_SHOWN = Array.from({ length: 17 }, (_, i) => i + 7)  // 07:00–23:00

export default function Stats() {
  const [s, setS] = useState(null)
  const [staff, setStaff] = useState(null)

  useEffect(() => {
    api('/api/stats').then(setS).catch(console.error)
    api('/api/stats/staff').then(setStaff).catch(console.error)
  }, [])
  if (!s) return <main><p className="hint">Loading analytics…</p></main>

  const on = key => s.panels?.[key] !== false
  const allHidden = s.panels && Object.values(s.panels).every(v => v === false)

  const dayMax = Math.max(1, ...s.revenue_by_day.map(d => d.revenue_cents))
  const hourMax = Math.max(1, ...s.by_hour.map(h => h.orders))
  const shortDay = iso => iso.slice(5)  // MM-DD

  return (
    <main className="stats-page">
      {allHidden && (
        <p className="hint">
          All statistics panels are switched off — turn them back on in
          Admin → Statistics panels.
        </p>
      )}

      {on('summary') && (
      <section className="stats">
        <div className="stat"><b>{s.total_orders}</b><span>orders total</span></div>
        <div className="stat"><b>{euro(s.total_revenue_cents)}</b><span>revenue total</span></div>
        <div className="stat"><b>{euro(s.avg_order_cents)}</b><span>avg order</span></div>
        <div className="stat"><b>{s.peak_hour != null ? `${s.peak_hour}:00` : '–'}</b><span>peak hour</span></div>
      </section>
      )}

      {on('revenue_by_day') && (
      <section className="panel">
        <h3>Revenue · last 14 days</h3>
        <div className="bar-chart">
          {s.revenue_by_day.map(d => (
            <div key={d.date} className="bar-col" title={`${d.date}: ${euro(d.revenue_cents)}`}>
              <div className="bar-fill"
                style={{ height: `${Math.round(100 * d.revenue_cents / dayMax)}%` }} />
              <span className="bar-label">{shortDay(d.date)}</span>
            </div>
          ))}
        </div>
      </section>
      )}

      {on('by_hour') && (
      <section className="panel">
        <h3>Busiest hours <span className="hint small">· by order count</span></h3>
        <div className="bar-chart">
          {HOURS_SHOWN.map(h => {
            const row = s.by_hour[h] || { orders: 0, revenue_cents: 0 }
            const peak = h === s.peak_hour
            return (
              <div key={h} className="bar-col"
                title={`${h}:00 — ${row.orders} orders, ${euro(row.revenue_cents)}`}>
                <div className={peak ? 'bar-fill peak' : 'bar-fill'}
                  style={{ height: `${Math.round(100 * row.orders / hourMax)}%` }} />
                <span className="bar-label">{h}</span>
              </div>
            )
          })}
        </div>
      </section>
      )}

      {on('staff') && staff && staff.staff.length > 0 && (
        <section className="panel">
          <h3>Staff performance <span className="hint small">· last {staff.days} days</span></h3>
          <p className="hint small">
            Team average: {euro(staff.team.avg_order_cents)} per order ·
            {' '}{staff.team.attach_rate_pct}% of orders include a paid extra.
          </p>
          <table className="staff-table">
            <thead>
              <tr>
                <th>Waiter</th>
                <th>Orders</th>
                <th>Revenue</th>
                <th title="Average value of an order they took">Avg check</th>
                <th title="Items per order - a proxy for suggestive selling">Items/order</th>
                <th title="Share of their orders that include a paid extra">Attach rate</th>
                <th title="Revenue generated by paid extras alone">Extras</th>
                <th>Share</th>
              </tr>
            </thead>
            <tbody>
              {staff.staff.map(w => {
                const better = w.avg_order_cents >= staff.team.avg_order_cents
                const strong = w.attach_rate_pct >= staff.team.attach_rate_pct
                return (
                  <tr key={w.waiter} className={w.active ? '' : 'off'}>
                    <td>
                      {w.waiter}
                      {!w.active && <span className="hint small"> · off</span>}
                    </td>
                    <td>{w.orders}<span className="sub">{w.orders_per_day}/day</span></td>
                    <td>{euro(w.revenue_cents)}</td>
                    <td className={better ? 'metric-good' : ''}>
                      {euro(w.avg_order_cents)}
                    </td>
                    <td>{w.items_per_order}</td>
                    <td className={strong ? 'metric-good' : ''}>
                      <div className="cum-cell">
                        <div className="cum-bar" style={{ width: `${w.attach_rate_pct}%` }} />
                        <span>{w.attach_rate_pct}%</span>
                      </div>
                    </td>
                    <td>{euro(w.extras_revenue_cents)}</td>
                    <td>{w.revenue_share_pct}%</td>
                  </tr>
                )
              })}
            </tbody>
          </table>
          <p className="hint small">
            Green marks a figure at or above the team average. Read these
            alongside context - a waiter on a quiet zone or a short shift
            will show lower volume without being a weaker seller. Avg check
            and attach rate are the fairest comparison, since they measure
            how well each order was sold rather than how many arrived.
          </p>
        </section>
      )}

      {on('pareto') && (
      <section className="panel">
        <h3>Pareto · the 80/20 of the menu</h3>
        {s.total_orders === 0 ? <p className="hint">No sales yet.</p> : (
          <>
            <p className="pareto-headline">
              <b>{s.pareto_count}</b> of {s.pareto_total_products} products
              drive <b>80%</b> of revenue.
            </p>
            <table>
              <thead><tr><th>Product</th><th>Revenue</th><th>Sold</th><th>Cumulative</th></tr></thead>
              <tbody>
                {s.pareto.map((p, i) => (
                  <tr key={p.name} className={i < s.pareto_count ? 'vital-few' : ''}>
                    <td>{p.name}</td>
                    <td>{euro(p.revenue_cents)}</td>
                    <td>{p.qty}</td>
                    <td>
                      <div className="cum-cell">
                        <div className="cum-bar" style={{ width: `${p.cumulative_pct}%` }} />
                        <span>{p.cumulative_pct}%</span>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        )}
      </section>
      )}

      {on('affinity') && (
      <section className="panel">
        <h3>Sold together <span className="hint small">· product affinity</span></h3>
        {s.affinity.length === 0 ? (
          <p className="hint">Not enough multi-item orders yet to find pairings.</p>
        ) : (
          <>
            <table>
              <thead><tr><th>Pairing</th><th>Orders</th><th>Support</th><th>Lift</th></tr></thead>
              <tbody>
                {s.affinity.map(p => (
                  <tr key={`${p.a}|${p.b}`}>
                    <td>{p.a} <span className="plus">+</span> {p.b}</td>
                    <td>{p.count}</td>
                    <td>{p.support_pct}%</td>
                    <td className={p.lift >= 1.5 ? 'lift-strong' : ''}>{p.lift}×</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <p className="hint small">
              Lift &gt; 1 means the two sell together more than chance would
              predict — candidates for a combo or a suggestive-sell prompt.
            </p>
          </>
        )}
      </section>
      )}
    </main>
  )
}
